name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Amazon Corretto JDK 21
    - name: Set up JDK 21 (Amazon Corretto)
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'

    # 3. Iniciar la base de datos con Docker
    - name: Start MySQL Database with Docker
      run: |
        docker run -ti --rm -d --name mysql_local -p 3306:3306 alvareitor01/desarrollo_iw
        sleep 10
        docker ps

    # 3. Construir el proyecto con Maven
    - name: Build with Maven
      run: mvn clean package
      working-directory: ./source/proYectFlow

    # 4. Configurar SSH
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    # 5. Desplegar el JAR en la máquina virtual de Azure
    - name: Deploy to Azure VM
      run: |
        scp ./source/proYectFlow/target/*.jar DaniFlow@proyectflow.westeurope.cloudapp.azure.com:/home/DaniFlow/proYectFlow/proyectflow.jar
        ssh DaniFlow@proyectflow.westeurope.cloudapp.azure.com << 'EOF'
          sudo systemctl stop proyectflow || true
          systemctl start proyectflow
        EOF
